apiVersion: gpu.scheduler.io/v1alpha1
kind: CUDAExperiment
metadata:
  name: cuda-kernel-memory
  namespace: default
spec:
  image: kratos-gpu-kernel-test:dev
  command:
    - /usr/local/bin/gpu-kernel
  arguments:
    - memory
  runtimeClassName: nvidia
  replicas: 1
  gpuRequired: 1
  profilingEnabled: true
