---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - gpu.scheduler.io
  resources:
  - cudaexperiments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gpu.scheduler.io
  resources:
  - cudaexperiments/finalizers
  verbs:
  - update
- apiGroups:
  - gpu.scheduler.io
  resources:
  - cudaexperiments/status
  - workloadprofiles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gpu.scheduler.io
  resources:
  - workloadprofiles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
