/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

// WorkloadBoundType classifies the dominant resource bottleneck observed for a workload.
type WorkloadBoundType string

const (
	WorkloadBoundCompute WorkloadBoundType = "compute-bound"
	WorkloadBoundMemory  WorkloadBoundType = "memory-bound"
	WorkloadBoundMixed   WorkloadBoundType = "mixed"
	WorkloadBoundUnknown WorkloadBoundType = "unknown"
)

// WorkloadProfileSpec defines the desired state of WorkloadProfile.
type WorkloadProfileSpec struct {
	// workloadImage is the CUDA workload container image that was profiled.
	// +optional
	WorkloadImage string `json:"workloadImage,omitempty"`

	// command is the workload entrypoint used during profiling.
	// +optional
	Command []string `json:"command,omitempty"`

	// arguments are passed to the workload command during profiling.
	// +optional
	Arguments []string `json:"arguments,omitempty"`

	// sourceCudaExperiment is the CUDAExperiment that requested this profile.
	// +optional
	SourceCUDAExperiment string `json:"sourceCudaExperiment,omitempty"`
}

// WorkloadProfileStatus defines the observed state of WorkloadProfile.
type WorkloadProfileStatus struct {
	// boundType is the dominant resource bottleneck observed for the workload.
	// +kubebuilder:validation:Enum=compute-bound;memory-bound;mixed;unknown
	// +optional
	BoundType WorkloadBoundType `json:"boundType,omitempty"`

	// metrics contains parsed profiling metric values keyed by metric name.
	// +optional
	Metrics map[string]string `json:"metrics,omitempty"`

	// nsightReportPath is the path to the Nsight Compute report generated by profiling.
	// +optional
	NsightReportPath string `json:"nsightReportPath,omitempty"`

	// conditions represent the current state of the WorkloadProfile resource.
	// Each condition has a unique type and reflects the status of a specific aspect of the resource.
	//
	// Standard condition types include:
	// - "Available": the resource is fully functional
	// - "Progressing": the resource is being created or updated
	// - "Degraded": the resource failed to reach or maintain its desired state
	//
	// The status of each condition is one of True, False, or Unknown.
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// WorkloadProfile is the Schema for the workloadprofiles API
type WorkloadProfile struct {
	metav1.TypeMeta `json:",inline"`

	// metadata is a standard object metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// spec defines the desired state of WorkloadProfile
	// +required
	Spec WorkloadProfileSpec `json:"spec"`

	// status defines the observed state of WorkloadProfile
	// +optional
	Status WorkloadProfileStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

// WorkloadProfileList contains a list of WorkloadProfile
type WorkloadProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []WorkloadProfile `json:"items"`
}

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypes(SchemeGroupVersion, &WorkloadProfile{}, &WorkloadProfileList{})
		return nil
	})
}
